language: python

python:
  - 3.8
cache: pip

before_install:
  - python --version
  - pip install -U pip
  - pip install -U flask
  - pip install requests
  - pip install flake8 codecov pytest pytest-cov
  
script: - pytest test_add.py
        - pytest --cov test_add.py

after_success:
        bash <(curl -s https://codecov.io/bash)

